version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:6.2-alpine
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  studentbatch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_batch_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${LIVE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${LIVE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${LIVE_DB_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: ${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA}
      BATCH_UPLOAD_DIRECTORY: ${BATCH_UPLOAD_DIRECTORY}
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data

volumes:
  postgres_data:
  pgadmin_data:
